function proiect(vi,r,c,tip_semnal,f,n,units)

T=1/f;
w=2*pi*f;
w0=(-1)/(r*c*10^(-6));
t=0:T/100:n*T;


Fig=figure('Name','Circuit integrator cu RC',...
    'Units','normalized',...
    'Position',[0.05 0.2 0.9 0.7],...
    'Color','#55473a' );

intr=uibuttongroup('Visible', 'on', ...   %bloc date intrare
   'ForegroundColor','w',...
   'Title','Date de Intrare',...
   'BackgroundColor','#54384c', ... 
   'Tag','intr',...
   'FontSize',10,...
   'TitlePosition','centertop',...
   'Position',[0.07 0.5 0.2 0.5]);

uicontrol('Style','text',...     %intrare rezistenta
    'Units','normalized',...
    'String','R=' ,...
   'Parent', intr,...
   'Position',[0.03 0.6 0.1 0.1],...
   'ForegroundColor','w',...
    'BackgroundColor','#54384c');
uicontrol('Style','edit',...
    'Units','normalized',...
    'Position',[0.10 0.65 0.35 0.05],...
    'String',num2str(r),...
    'Parent',intr, ...
    'Callback','r=str2num(get(gco,''String''));close;proiect(vi,r,c,tip_semnal,f,n,units);');


uicontrol('Style','text',...       %intrare amplitudine semnal
    'Units','normalized',...
    'String','Vi' ,...
   'Parent', intr,...
   'Position',[0.02 0.84 0.1 0.06],...
   'ForegroundColor','w',...
    'BackgroundColor','#54384c');

   if vi>7 
      vi=7;
   elseif vi<0
       vi=0;
   end

Bs=uicontrol('Style','slide',...      
    'Units','normalized',...
    'Position',[0.15 0.84 .40 .06],...,
    'Parent', intr, ...
    'Min',0,'Max', 7,'Value',vi,...
    'Callback','vi=get(gco,''Value'');close;proiect(vi,r,c,tip_semnal,f,n,units);') ;

uicontrol('Style','text',...   
    'Units','normalized',...
    'Position',[0.10 0.84 0.05 0.06],...
    'Parent', intr, ...
    'String',num2str(get(Bs,'Min')));
uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.55 0.84 0.05 0.06],...
    'Parent', intr, ...
    'foregroundcolor','black',...
    'String',num2str(get(Bs,'Max')));
uicontrol('Style', 'edit',...
    'Units', 'normalized',...
    'Position',[0.60 0.84 0.06 0.06],...
    'Parent', intr, ...
    'String', num2str(vi), ...
    'Callback', 'vi=str2num(get(gco,''String''));close;proiect(vi,r,c,tip_semnal,f,n,units);');


  
uicontrol('Style','text',...         %intrare condensator
    'Units','normalized',...
    'String','C=' ,...
   'Parent', intr,...
   'Position',[0.02 0.5 0.1 0.1],...
   'ForegroundColor','w',...
    'BackgroundColor','#54384c');
uicontrol('Style','edit',...
    'Units','normalized',...
    'Position',[0.10 0.55 0.35 0.05],...
    'String',num2str(c),...
    'Parent',intr, ...
    'Callback','c=str2num(get(gco,''String''));close;proiect(vi,r,c,tip_semnal,f,n,units);');


uicontrol('Style','text',...     %intrare tip semnal
    'Units','normalized',...
    'String','Tip semnal=' ,...
   'Parent', intr,...
   'Position',[0.001 0.7 0.15 0.1],...
   'ForegroundColor','w',...
    'BackgroundColor','#54384c');

uicontrol("Style","popupmenu",...
    "Units","normalized",...
    "Position",[ 0.17 .70 .3 .1 ],...
    "Parent",intr,...
    "Value",tip_semnal,...
    "String",'Sinus|Cosinus|Dreptunghi|Triunghi', ...
    "Callback",'tip_semnal=get(gco, ''Value'');close;proiect(vi,r,c,tip_semnal,f,n,units);');

uicontrol('Style','text',...     %intrare numar perioade
    'Units','normalized',...
    'String','Nr perioade=' ,...
   'Parent', intr,...
   'Position',[0.001 0.4 0.19 0.1],...
   'ForegroundColor','w',...
    'BackgroundColor','#54384c');
uicontrol('Style','edit',...
    'Units','normalized',...
    'Position',[0.20 0.45 0.3 0.05],...
    'String',num2str(n),...
    'Parent',intr, ...
    'Callback','n=str2num(get(gco,''String''));close;proiect(vi,r,c,tip_semnal,f,n,units);');

uicontrol('Style','text',...     %intrare frecventa
    'Units','normalized',...
    'String','f=' ,...
   'Parent', intr,...
   'Position',[0.001 0.3 0.15 0.1],...
   'ForegroundColor','w',...
    'BackgroundColor','#54384c');
uicontrol('Style','edit',...
    'Units','normalized',...
    'Position',[0.14 0.35 0.3 0.05],...
    'String',num2str(f),...
    'Parent',intr, ...
    'Callback','f=str2num(get(gco,''String''));close;proiect(vi,r,c,tip_semnal,f,n,units);');




switch tip_semnal  %forma de unda la intrare 

    case 1
        sem_in= vi.*sin(w.*t);
    case 2
        sem_in=vi.*cos(w.*t);
    case 3
        sem_in=vi.*square(w.*t);
    case 4
        sem_in=(2*vi/pi)*asin(sin(w.*t));
    
    
end

switch tip_semnal  %forma de unda integrata 

    case 1
        fun = @(t) vi * sin(w* t+pi); 

Vout2 = ones(1,length(t)-50); 
for i = 1:(length(t)-50)
Vout2(i) = w0*integral(fun,t(i),t(i+50));

end
    case 2
        fun = @(t) vi * cos(w* t+pi); 

Vout2 = ones(1,length(t)-50); 
for i = 1:(length(t)-50)
Vout2(i) = w0*integral(fun,t(i),t(i+50));
end  
case 3
        fun = @(t) vi * square(w* t+pi); 

Vout2 = ones(1,length(t)-50); 
for i = 1:(length(t)-50)
Vout2(i) = w0*integral(fun,t(i),t(i+50));
end
    case 4
              fun = @(t) (2*vi/pi)*asin(sin(w.*t+pi)); 

Vout2 = ones(1,length(t)-50); 
for i = 1:(length(t)-50)
Vout2(i) = w0*integral(fun,t(i),t(i+50));
end 
end


Iin=vi/r;
Xc=1/(w*c*10^(-6));
Av=-Xc/r;

outp=uibuttongroup('Visible', 'on', ... %bloc date calculate
   'ForegroundColor','w',...
   'Title','Date Calculate',...
   'BackgroundColor','#54384c', ... 
   'Tag','outp',...
   'FontSize',10,...
   'TitlePosition','centertop',...
   'Position',[0.27 0.5 0.2 0.5]);
uicontrol('Style','text',...
    'Units','normalized',...
    'String','Iin=Ic=' ,...
   'Parent', outp,...
   'Position',[0.04 0.5 0.2 0.1],...
   'ForegroundColor','w',...
    'BackgroundColor','#54384c');
uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.20 0.55 0.35 0.05],...
    'String',num2str(Iin*10^3),...
    'Parent',outp);


uicontrol('Style','text',...
    'Units','normalized',...
    'String','Xc=' ,...
   'Parent', outp,...
   'Position',[0.005 0.6 0.3 0.1],...
   'ForegroundColor','w',...
    'BackgroundColor','#54384c');
uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.20 0.65 0.35 0.05],...
    'String',num2str(Xc),...
    'Parent',outp);
uicontrol('Style','text',...
    'Units','normalized',...
    'String','Av=' ,...
   'Parent', outp,...
   'Position',[0.005 0.7 0.3 0.1],...
   'ForegroundColor','w',...
    'BackgroundColor','#54384c');
uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.20 0.75 0.35 0.05],...
    'String',num2str(Av),...
    'Parent',outp);

uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.20 0.45 0.35 0.05],...
    'String',num2str(T*10^3),...
    'Parent',outp);
uicontrol('Style','text',...
    'Units','normalized',...
    'String','T=' ,...
   'Parent', outp,...
   'Position',[0.1 0.4 0.1 0.1],...
   'ForegroundColor','w',...
    'BackgroundColor','#54384c');

uicontrol('Style','checkbox',...
    'Units','normalized',...
    'Position',[0.20 0.15 0.45 0.05],...
    'String', 'Unitati de masura', ...
    'Value',units,...
    'Parent',intr,...
    'Callback','units=(get(gco, ''Value''));close;proiect(vi,r,c,tip_semnal,f,n,units);');
if units==1                        %unitati de masura
    uicontrol('Style','text',...     
    'Units','normalized',...
    'String','Ω' ,...
   'Parent', intr,...
   'Position',[0.45 0.6 0.04 0.1],...
   'ForegroundColor','w',...
    'BackgroundColor','#54384c');
    uicontrol('Style','text',...     
    'Units','normalized',...
    'String','Ω' ,...
   'Parent', outp,...
   'Position',[0.56 0.6 0.04 0.1],...
   'ForegroundColor','w',...
    'BackgroundColor','#54384c');
        uicontrol('Style','text',...     
    'Units','normalized',...
    'String','Hz' ,...
   'Parent', intr,...
   'Position',[0.45 0.3 0.09 0.1],...
   'ForegroundColor','w',...
    'BackgroundColor','#54384c');
        uicontrol('Style','text',...
    'Units','normalized',...
    'String',' μF ' ,...
   'Parent', intr,...
   'Position',[0.45 0.5 0.09 0.1],...
   'ForegroundColor','w',...
    'BackgroundColor','#54384c');
        uicontrol('Style','text',...
    'Units','normalized',...
    'String','V' ,...
   'Parent', intr,...
   'Position',[0.67 0.84 0.04 0.06],...
   'ForegroundColor','w',...
    'BackgroundColor','#54384c');
        uicontrol('Style','text',...
    'Units','normalized',...
    'String','mA' ,...
   'Parent', outp,...
   'Position',[0.56 0.5 0.09 0.1],...
   'ForegroundColor','w',...
    'BackgroundColor','#54384c');
             uicontrol('Style','text',...
    'Units','normalized',...
    'String','ms' ,...
   'Parent', outp,...
   'Position',[0.56 0.4 0.09 0.1],...
   'ForegroundColor','w',...
    'BackgroundColor','#54384c');
end


subplot(122) %grafic

plot(t,sem_in,'r','LineWidth',2);
hold on;
title("Tensiunea de intrare in raport cu iesirea");
grid("on");
xlabel('t[ms]');
ylabel('Vi[V]');
plot(t(1:end-50),Vout2,'blue','LineWidth',1.5);
legend('Vi','Vo');



subplot(223)
x=imread("Circuit.png");
image(x); 

%documentatie

f=uimenu('Label','Documentatie');
uimenu(f,'Label','Bibliografia','Callback','open("Documentatie.htm")');
uimenu(f,'Label','Curs ETTI','Callback','open("DE_Curs9.pdf")');
uimenu(f,'Label','Youtube','Callback','open("YT.htm")');
uimenu(f,'Label','powerPoint priect','Callback','open("proiectgac.pptx")');
uicontrol('Style','pushbutton',...
    'Units','normalized',...
    'Position',[0.20 0.15 0.35 0.05],...
    'String','Reset',...
    'Parent',outp,...
    'Callback','close;proiect(2,1000,2,1,1000,2,0);');

end